### ISSUE TITLE
Trimpot calibration

### ISSUE THREAD

**Issue by zerbian** [MyModularJourney/1U_Attenuverter#1]
Hey,
I look thrugh the documentation and build guide and found nothing in reagrds to the trimpot and calibrating the module.
On the last pages it says: No calibration required, but what is trimpots use then?

Thanks!

**Comment by MyModularJourney** [comment]
Hey,

I missed that part completely. My apologies.

If you use a centre detent potentiometer, you can use it to make it zero
exactly right.
If you have a regular pot, you can leave it at the factory position. Which
should be pretty much in the middle of the range. Even two 47k resistors
would work.

I will fix the documentation asap. Thanks for reaching out!


Bas

**Comment by zerbian** [comment]
Alright, thank you for your super quick response!

**Comment by MyModularJourney** [comment]
Hey,

I have uploaded an updated build document version 1.2.
Thanks so much for your feedback and pointing out this issue!


Bas
